# Generated by Django 4.2.2 on 2023-09-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_alter_company_id_alter_project_id_alter_tag_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": [
                    models.OrderBy(
                        models.F("end_date"), descending=True, nulls_first=True
                    )
                ]
            },
        ),
    ]
