# Generated by Django 4.2.2 on 2023-09-23 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_project_options_alter_project_actual_design_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="actual_design",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Actual design hours",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="actual_development",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Actual development hours",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="actual_testing",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Actual testing hours",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Project end date"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Project start date"
            ),
        ),
    ]
